### PR TITLE
Extract Church Center url helper methods from new login form

### PR DESCRIPTION
**Pull request by danott**
While spiking the future of Church Center Website's login, these two utility functions came in handy. Using `buildSubdomain` to translate from the runtime domain to another subdomain was particularly useful for building the `http://api.churchcenter.test` origin. `buildUrl` is helpful for linking to anything on Church Center from any Church Center domain or Planning Center domain.

This is a very different approach to building URLs in JavaScript from the existing `alpha-1` version. From what I can find in our internal packages, `@churchcenter/url` on appears within a single `packages.json`. And within that package, it's never actually used.  I considered putting this package under a new name, but if we aren't using the previous, it feels preferable to have the `url` name because that is what our future selves will most likely be looking for.

Also worth noting, I added minimal configs for eslint and prettier to the monorepo's `package.json`. This is an opinoin that might be better suited for another Pull Request, but it seemed like the right time to set a precedent for the future of this monorepo as we extract more things that will be useful across all Planning Center applications that are represented on Church Center.

### CODE REVIEW

**Comment by chantastic** [comment]
@danott I think you should take over here, provided @shanebonham doesn't have any stock in this implementation.

I had set this up here simply to namespace the project.
But I'm thinking it won't scale for the direction we're taking Global Design.

I'm wondering, if it stays a monorepo, if we should just move it back into the `planningcenter` org and rename the repo `churchcenter`. Might be nice to piggyback on that orgs permissions.

**Comment by shanebonham** [comment]
Our usage of it was removed here: https://github.com/ministrycentered/people/pull/4368/files (the package should have been removed, but wasn't). Hence, I have no strong feelings about this discussion!

**Comment by danott** [comment]
I also agree that fewer GitHub organizations is preferable. 100% onboard with that move, regardless of what actually lives inside the repo. 

@chantastic I'd predict I'll need to lean heavily on your know-how and experience for ensuring that our package.json is correctly setup for monorepo consumption. Right now, `@planningcenter/url` resolves to `planningcenter/javascript/packages/url`. With having multiple repos that are serving up JavaScript, I'm wondering what the ideal import statements look like (and how to configure them)? `@planningcenter/churchcenter/url` mapping to `planningcenter/churchcenter/packages/url`? `@planningcenter/churchcenter-url` mapping to `planningcenter/churchcenter/packages/url`? (What I'm trying to highlight, is I don't know the constraints of workspaces, lerna, etc for managing monorepos)

With the consideration of moving, could it also make sense to merge the contents of this repo into the existing `planningcenter/javascript` repo? 
As an example, `churchcenter/javascript/packages/url` could become `planningcenter/javascript/packages/churchcenterurl`?

Maybe that's a terrible idea. I thought it worth asking because it struck me funny when I considered  having a plurality of monorepos. 🙃 The initial downside I could see to that is that we may not want `planningcenter/javascript` to adopt the `prettier` and `ESLint` config that lives in the root of this monorepo. There are other downsides I'd imagine?

I know you've thought through these constraints a lot. Is there an ideal setup you'd want to aim for to strike the balance of namespacing things clearly while reaping the benefits of consistent permissions in a single GitHub organization/repo?

**Comment by chantastic** [comment]
✅ took the first step, moving this back into the @planningcenter org.

you're added as an admin. please create your church center team on the @planningcenter org and we'll add it

**Comment by chantastic** [comment]
I believe the import path issue you were experiencing was just a bad build where the `/dist` directory wasn't published.

If you look at `v1.0.1` on [unpkg.com], you'll see that the `@churchcenter/url` package index will direct to the right file (according to env).
`@churchcenter/javascript` is not a published package.
So developers shouldn't have the option adding all JavaScript and including it through the `@churchcenter/javascript/packages/url/dist/url.js` path.

**Pull request merged**
